"""StructAI Python bridge — FastAPI entry point.

Binds to 127.0.0.1 only. Exposes:
  GET  /status              — health check the app polls.
  POST /resync              — force an immediate read + post.
  POST /push-combinations   — receive app-generated combos to inject
                              back into STAAD. Phase 1 scope: log only;
                              actual STAAD writing lands when the COM
                              write path is built out.

Background task: every POLL_INTERVAL seconds, hash the .std file and
post a fresh SyncPayload if the hash changed. See docs/13-bridge.md.
"""
from __future__ import annotations

import asyncio
import logging
from contextlib import asynccontextmanager
from typing import Optional

from fastapi import FastAPI, HTTPException

from config import Config, load_config
from payload import PushCombinationsBody, ResyncBody
from staad_reader import StaadError, file_sha256, read_model
from sync_client import post_sync

logger = logging.getLogger("staad-bridge")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


class BridgeState:
    def __init__(self, cfg: Config) -> None:
        self.cfg = cfg
        self.last_hash: Optional[str] = None
        self.last_error: Optional[str] = None

    def current_hash(self) -> Optional[str]:
        if self.cfg.mock_mode:
            # Mock mode: hash is computed from the payload itself; we
            # poll once at startup and never auto-re-sync.
            return self.last_hash
        if self.cfg.staad_file_path is None:
            return None
        if not self.cfg.staad_file_path.exists():
            return None
        return file_sha256(self.cfg.staad_file_path)


STATE: Optional[BridgeState] = None


async def poll_loop(state: BridgeState) -> None:
    """Every POLL_INTERVAL seconds: check hash, sync if changed."""
    while True:
        try:
            await _sync_if_changed(state)
        except Exception as e:  # noqa: BLE001 — keep the loop alive
            state.last_error = str(e)
            logger.exception("poll_loop error")
        await asyncio.sleep(state.cfg.poll_interval_s)


async def _sync_if_changed(state: BridgeState) -> None:
    cfg = state.cfg
    if cfg.mock_mode:
        # Sync once at startup and then never; the dev workflow is to
        # hit POST /resync manually when you want fresh mock data.
        if state.last_hash is not None:
            return

    current = state.current_hash()
    if current is None and not cfg.mock_mode:
        return
    if current == state.last_hash:
        return

    payload = read_model(cfg.project_id, cfg.staad_file_path, cfg.mock_mode)
    result = post_sync(cfg.app_url, cfg.bridge_secret, payload)
    if result.ok:
        state.last_hash = payload.file_hash
        state.last_error = None
        logger.info(
            "sync ok: file=%s hash=%s counts=%s",
            payload.file_name,
            payload.file_hash[:8],
            result.data.get("counts") if result.data else "?",
        )
    else:
        state.last_error = result.error
        logger.error("sync failed: %s", result.error)


@asynccontextmanager
async def lifespan(_app: FastAPI):
    cfg = load_config()
    global STATE
    STATE = BridgeState(cfg)
    logger.info(
        "starting bridge · project=%s mock=%s app=%s",
        cfg.project_id, cfg.mock_mode, cfg.app_url,
    )
    task = asyncio.create_task(poll_loop(STATE))
    try:
        yield
    finally:
        task.cancel()


app = FastAPI(title="StructAI Bridge", lifespan=lifespan)


def _state() -> BridgeState:
    if STATE is None:
        raise HTTPException(status_code=503, detail="bridge not ready")
    return STATE


@app.get("/status")
def status():
    s = _state()
    return {
        "ok": True,
        "project_id": s.cfg.project_id,
        "mock_mode": s.cfg.mock_mode,
        "last_hash": s.last_hash,
        "last_error": s.last_error,
    }


@app.post("/resync")
async def resync(body: ResyncBody):
    s = _state()
    if body.project_id != s.cfg.project_id:
        raise HTTPException(
            status_code=400,
            detail=f"project_id mismatch: bridge is bound to {s.cfg.project_id}",
        )
    # Force a sync regardless of hash.
    s.last_hash = None
    try:
        await _sync_if_changed(s)
    except StaadError as e:
        raise HTTPException(status_code=500, detail=str(e))
    if s.last_error:
        raise HTTPException(status_code=500, detail=s.last_error)
    return {"ok": True, "hash": s.last_hash}


@app.post("/push-combinations")
def push_combinations(body: PushCombinationsBody):
    """Receive combos generated by the app.

    Phase 1 scope: log them. Writing them back into the STAAD model
    requires the OpenSTAAD Load + SetLoadCombinationFactor COM calls
    which are version-sensitive; that's a later commit. The app
    degrades gracefully when this endpoint no-ops (combos stay in
    Supabase with source='app_generated').
    """
    s = _state()
    if body.project_id != s.cfg.project_id:
        raise HTTPException(
            status_code=400,
            detail=f"project_id mismatch: bridge is bound to {s.cfg.project_id}",
        )
    logger.info(
        "push-combinations: received %d combos for project %s",
        len(body.combinations), body.project_id,
    )
    return {"ok": True, "received": len(body.combinations)}
